kind: Service
apiVersion: v1
metadata:
  name: mailserver
  namespace: humandb-01
  labels:
    app: mailserver
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  
spec:
  selector:
    app: mailserver
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
    - name: smtp-auth
      port: 587
      targetPort: smtp-auth
    - name: imap-secure
      port: 993
      targetPort: imap-secure

---
