apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-ref-hg38 ## This is where the ref genome is saved. #mounted at /ref-hg38
  namespace: argo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: rook-cephfs
---
