kind: Service
apiVersion: v1
metadata:
  name: oos-fe-service
  namespace: "oos-prod"
  labels:
    app: oos-fe
spec:
  type: NodePort
  selector:
    app: oos-fe
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: webhttp
