version: '2'
services:
  router:
    build: ./local/router
    depends_on:
      - hdb-dash-fe
      - hdb-dash-auth
    ports:
      - '80:80'
  hdb-dash-fe:
    build:
      context: ./dashboard/react/.
      dockerfile: Dockerfile-dev
    environment:
      NODE_PATH: src/
    command: yarn run start
    volumes:
      - ./dashboard/react/.:/var/www
      - /var/www/node_modules
  hdb-dash-auth:
    build: ./dashboard/api/.
    command: yarn run start-dev
    depends_on:
      - pgsql-dash
    env_file:
      - ./dashboard/api/.env.local
    volumes:
      - ./dashboard/api/.:/var/www
      - /var/www/node_modules
      - ./filesystem:/data
  hdb-adv-api:
    build: ./advaitabio/api
    volumes:
      - ./advaitabio/api/.:/var/www
      - /var/www/node_modules
      - ./filesystem:/data
  discourse-web:
    image: 413230511243.dkr.ecr.us-east-1.amazonaws.com/discourse-db01:latest
    command: /sbin/boot
    env_file:
      - ./discourse/.env.local
    volumes:
      - ./filesystem:/data
  test-container:
    build: ./local/test-container/.
    depends_on:
      - hdb-dash-auth
    volumes:
      - ./local/test-container/.:/var/www
      - /var/www/node_modules
      - ./filesystem:/data
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_DB: shared
      POSTGRES_USER: shared
      POSTGRES_PASSWORD: shared
    volumes:
      - ./filesystem/shared/pg:/var/lib/postgresql/data
  pgsql-dash:
    image: postgres:11.1
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: hdb-dash
      POSTGRES_PASSWORD: test
    volumes:
      - ./filesystem/services/dashboard/pg:/var/lib/postgresql/data
  pgsql-discourse:
    image: postgres:11.1
    environment:
      POSTGRES_DB: discourse
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - ./filesystem/services/discourse/pg:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3
    volumes:
      - ./filesystem/shared/redis:/data
  redis-discourse:
    image: redis:5.0.3
    volumes:
      - ./filesystem/services/discourse/redis:/data