kind: Service
apiVersion: v1
metadata:
  name: gatk-hdb01 #Update to reflect workspace name
  namespace: "humandb-01"
  labels:
    app: gatk-hdb01 #Use value from line 4
spec:
  type: NodePort
  selector:
    app: gatk-hdb01 #Use value from line 4
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: webhttp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatk-deployment
  namespace: "humandb-01"
  labels:
    app: gatk-hdb01 #Use value from line 4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatk-hdb01 #Use value from line 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: gatk-hdb01 #Use value from line 4
    spec:
      containers:
      - name: gatk-hdb01 #Use value from line 4
        image: 413230511243.dkr.ecr.us-east-1.amazonaws.com/gatk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hdbb01-raw-data
          mountPath: /hdb01-data
      volumes:
      - name: hdbb01-raw-data
        persistentVolumeClaim:
          claimName: hdb01-raw-pvc
